import os

INSTA_API_KEY = os.environ['INSTA_API_KEY']
INSTA_AUTH_TOKEN = os.environ['INSTA_AUTH_TOKEN']

TWITTER_CONSUMER_KEY = os.environ['TWITTER_CONSUMER_KEY']
TWITTER_CONSUMER_SECRET = os.environ['TWITTER_CONSUMER_SECRET']

TWITTER_OAUTH_TOKEN = os.environ['TWITTER_OAUTH_TOKEN']
TWITTER_OAUTH_SECRET = os.environ['TWITTER_OAUTH_SECRET']
